### ISSUE TITLE
Ability to use my default browser

### ISSUE THREAD

**Issue by duranmla** [loladotdev/lola#7]
### Describe the solution you'd like?

My default browser is Safari. I do have chrome to run my dev application but often my google searches and all other things are at Safari. Currently when I click the button for AWS Console from Lola or try to open a database row it opens Google Chrome

### Additional context

_I wonder if people without Chrome will have issues 🤔_

**Comment by livioso** [comment]
Thanks for the feedback! :) 

This behaviour [can be changed](https://github.com/loladotdev/lola/wiki/Settings#use-default-browser-for-aws-console-links) to always use the default browser (see also #3).

The idea behind this was to simplify using multiple accounts in parallel. How it works: To ensure you are logged into the correct AWS account we create a fresh browser profile for each account. The goal is to not mess with any AWS console session you may have already open in your browser. For now we support Chrome and Firefox based browsers and check if we can find any of those on your system or otherwise fallback to the default browser (Chrome being the first in the list).
